SC-7773 - stabilises rabbitMQ connection
hpi-schul-cloud/antivirus_check_service pull request #3
Opened 2020-12-01 08:28 UTC by virgilchiriac

# Description

The load on the system, coupled with expiration times, makes rabbitMQ drop connections, which leads to K8 pod restarts every few seconds.

In this PR we reduce the number of times a file is attemoted to downloaded, as well as the sleep time. This decrease the blocking connection from 31 seconds to 7 seconds.
At the same time, the heartbeat is specified to be 120 seconds.
The client also specifies heartbeat and timeout which can be configured via secrets/config.yml, as [recommended by pika](https://pika.readthedocs.io/en/stable/examples/heartbeat_and_blocked_timeouts.html)

## Links to Tickets or other pull requests
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7773

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-12-01 08:30 UTC, Parnswir approved these changes

2020-12-01 10:12 UTC, mamutmk5 requested changes
Where is the place where the exceptions who where thrown catched ?

2020-12-01 12:13 UTC, virgilchiriac commented on antivirus_service/handler.py
>              raise Exception('File could not downloaded: {0} - after {1} seconds'.format(last_exception_message, 2**(i+1) - 1))
when this exception is raised, is not gonna scan the file anymore, but the rabbitMQ connection will not terminate, and new requests can be processed

2020-12-01 16:04 UTC, mamutmk5 requested changes
Okay if pika lost the rabbitmy connection it don't reconnect.
See https://github.com/pika/pika#connection-recovery how to do it

2021-06-03 10:19 UTC, closed without merging

2021-06-03 10:21 UTC, virgilchiriac commented
branch renamed, new PR https://github.com/hpi-schul-cloud/antivirus_check_service/pull/5